// <auto-generated />
namespace ClinicalAthletes.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2017b : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2017b));
        
        string IMigrationMetadata.Id
        {
            get { return "201712311505485_2017b"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
